src/carts/urls.py
from django.urls import path

from .views import cart_home, cart_update, checkout_home

app_name = 'cart'

urlpatterns = [
    path('', cart_home, name='home'),
    path('update/', cart_update, name='update'),
    path('checkout/', checkout_home, name='checkout'),
]

src/ecommerce/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.contrib.auth.views import LogoutView
from django.conf.urls.static import static

from address.views import checkout_address_create_view, checkout_address_reuse_view
from accounts.views import login_page, guest_register_view
from carts.views import cart_detail_api_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
    path('search/', include('search.urls', namespace='search')),
    path('', include('accounts.urls', namespace='accounts')),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('api/cart/', cart_detail_api_view, name='api-cart'),
    path('cart/', include('carts.urls', namespace='cart')),
    path('login/', login_page, name='login'),
    path('checkout/address/create/', checkout_address_create_view,
         name='checkout_address_create'),
    path('checkout/address/reuse/', checkout_address_reuse_view,
         name='checkout_address_reuse'),
    path('register/guest/', guest_register_view, name='guest_register'),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + \
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + \
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/templates/base/css.html
{% load static %}

<link
  href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css"
  rel="stylesheet"
  integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1"
  crossorigin="anonymous"
/>

<!--Font Awesome-->
<link
  rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.css"
  integrity="sha512-9iWaz7iMchMkQOKA8K4Qpz6bpQRbhedFJB+MSdmJ5Nf4qIN1+5wOVnzg5BQs/mYH3sKtzY+DOgxiwMz8ZtMCsw=="
  crossorigin="anonymous"
/>

src/templates/base/js.html
{% load static %}

<script src="https://code.jquery.com/jquery-3.5.1.min.js"
  integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"
  integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js"
  integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>

src/templates/base/navbar.html
{% url 'cart:home' as cart_url %}
{% url 'login' as login_url %}
{% url 'logout' as logout_url %}
{% url 'register' as register_url %}

<nav class="navbar navbar-expand-lg navbar-light bg-info mb-3">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">eCommerce</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02"
      aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>

        {% if request.user.is_authenticated %}
        <li class="nav-item  {% if request.path == logout_url %}active{% endif %}">
          <a class="nav-link" href="{{logout_url}}">Logout</a>
        </li>


        {% else %}
        <li class="nav-item  {% if request.path == login_url %}active{% endif %}">
          <a class="nav-link" href="{{login_url}}">Login</a>
        </li>

        <li class="nav-item  {% if request.path == register_url %}active{% endif %}">
          <a class="nav-link" href="{{register_url}}">Register</a>
        </li>

        {% endif %}
        <li class="nav-item {% if request.path == cart_url %}active{% endif %}">
          <a class="nav-link" href="{{cart_url}}">
            <i class="fas fa-shopping-cart"></i>
            <span class="navbar-cart-count">{{request.session.cart_items}}</span>

          </a>
        </li>
      </ul>
      {% include 'search/templates/search/snippets/search-form.html' %}
    </div>
  </div>
</nav>