src/carts/urls.py
from django.urls import path

from .views import cart_home, cart_update, checkout_home

app_name = 'cart'

urlpatterns = [
    path('', cart_home, name='home'),
    path('update/', cart_update, name='update'),
    path('checkout/', checkout_home, name='checkout'),
]

src/ecommerce/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.contrib.auth.views import LogoutView
from django.conf.urls.static import static

from address.views import checkout_address_create_view, checkout_address_reuse_view
from accounts.views import login_page, guest_register_view
from carts.views import cart_detail_api_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
    path('search/', include('search.urls', namespace='search')),
    path('', include('accounts.urls', namespace='accounts')),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('api/cart/', cart_detail_api_view, name='api-cart'),
    path('cart/', include('carts.urls', namespace='cart')),
    path('login/', login_page, name='login'),
    path('checkout/address/create/', checkout_address_create_view,
         name='checkout_address_create'),
    path('checkout/address/reuse/', checkout_address_reuse_view,
         name='checkout_address_reuse'),
    path('register/guest/', guest_register_view, name='guest_register'),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + \
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + \
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/carts/models.py
from django.db.models.signals import pre_save, post_save, m2m_changed
from decimal import Decimal
from django.conf import settings
from django.db import models

from products.models import Product


class CartManager(models.Manager):
    def new_or_get(self, request):
        cart_id = request.session.get('cart_id', None)
        # qs = Cart.objects.filter(id=cart_id)
        qs = self.get_queryset().filter(id=cart_id)
        if qs.count() == 1:
            new_obj = False
            cart_obj = qs.first()
            if request.user.is_authenticated and cart_obj.user is None:
                cart_obj.user = request.user
                cart_obj.save()
        else:
            cart_obj = Cart.objects.new(user=request.user)
            new_obj = True
            request.session['cart_id'] = cart_obj.id
        return cart_obj, new_obj

    def new(self, user=None):
        user_obj = None
        if user is not None:
            if user.is_authenticated:
                user_obj = user
        return self.model.objects.create(user=user_obj)


class Cart(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE, null=True, blank=True)
    products = models.ManyToManyField(Product, blank=True)
    total = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    subtotal = models.DecimalField(
        default=0.00, max_digits=100, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = CartManager()

    def __str__(self):
        return str(self.id)


def m2m_changed_cart_receiver(sender, instance, action, *args, **kwargs):
    if action == 'post_add' or action == 'post_remove' or action == 'post_clear':
        products = instance.products.all()
        total = 0
        for x in products:
            total += x.price
        if instance.subtotal != total:
            instance.subtotal = total
            instance.save()


m2m_changed.connect(m2m_changed_cart_receiver, sender=Cart.products.through)


def pre_save_cart_receiver(sender, instance, *args, **kwargs):
    if instance.subtotal > 0:
        instance.total = Decimal(instance.subtotal) * Decimal(1)
    else:
        instance.total = 0.00


pre_save.connect(pre_save_cart_receiver, sender=Cart)

src/carts/views.py
from django.http import JsonResponse
from django.views.generic.base import TemplateView
from django.shortcuts import render, HttpResponse, redirect

from .models import Cart
from address.models import Address
from address.forms import AddressForm
from accounts.forms import LoginForm, GuestForm
from accounts.models import GuestEmail
from billing.models import BillingProfile
from orders.models import Order
from products.models import Product


class CartView(TemplateView):
    template_name = "carts/home.html"

    def get_context_data(self, **kwargs):
        # get session data
        cart_id = self.request.session.get('cart_id', None)
        if cart_id is None:  # and isinstance(cart_id, int):
            print('create new cart')
            # self.request['cart_id']
        else:
            print('Cart ID exists')
        session = self.request.session


def cart_detail_api_view(request):
    cart_obj, new_obj = Cart.objects.new_or_get(request)

    products = [{'name': x.name, 'price': x.price}
                for x in cart_obj.products.all()]
    cart_data = {'products': products,
                 'subtotal': cart_obj.subtotal, 'total': cart_obj.total}
    return JsonResponse(cart_data)


def cart_home(request):
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    return render(request, 'carts/home.html', {"cart": cart_obj})


def cart_update(request):
    product_id = request.POST.get('product_id')

    if product_id is not None:
        try:
            product_obj = Product.objects.get(id=product_id)
        except Product.DoesNotExist:
            return redirect("cart:home")
        cart_obj, new_obj = Cart.objects.new_or_get(request)
        if product_obj in cart_obj.products.all():
            cart_obj.products.remove(product_obj)
            added = False
        else:
            cart_obj.products.add(product_obj)
            added = True
        request.session['cart_items'] = cart_obj.products.count()

        if request.is_ajax():
            print('Ajax')
            json_data = {
                'added': added,
                'removed': not added,
                'cartItemCount': cart_obj.products.count()
            }
            return JsonResponse(json_data)

    return redirect("cart:home")


def checkout_home(request):
    cart_obj, cart_created = Cart.objects.new_or_get(request)
    order_obj = None
    if cart_created or cart_obj.products.count() == 0:
        return redirect("cart:home")

    login_form = LoginForm()
    guest_form = GuestForm()
    address_form = AddressForm()

    billing_address_id = request.session.get('billing_address_id', None)
    shipping_address_id = request.session.get('shipping_address_id', None)

    billing_profile, billing_profile_created = BillingProfile.objects.new_or_get(
        request)

    address_qs = None
    if billing_profile is not None:
        if request.user.is_authenticated:
            address_qs = Address.objects.filter(
                billing_profile=billing_profile)
        order_obj, order_obj_created = Order.objects.new_or_get(
            billing_profile, cart_obj)
        if shipping_address_id:
            order_obj.shipping_address = Address.objects.get(
                id=shipping_address_id)
            del request.session['shipping_address_id']
        if billing_address_id:
            order_obj.billing_address = Address.objects.get(
                id=billing_address_id)
            del request.session['billing_address_id']
        if billing_address_id or shipping_address_id:
            order_obj.save()

    if request.method == 'POST':
        """ some check that order is done """
        is_done = order_obj.check_done()
        if is_done:
            order_obj.mark_paid()
            request.session['cart_items'] = 0
            del request.session['cart_id']
        return redirect('/cart/success')

    context = {
        'object': order_obj,
        'billing_profile': billing_profile,
        'login_form': login_form,
        'guest_form': guest_form,
        'address_form': address_form,
        'address_qs': address_qs
    }
    return render(request, 'carts/checkout.html', context)

src/carts/templates/carts/checkout.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
    {% if not billing_profile %}
    <div class="row text-center">
        <div class="col-12 col-md-6">
            <p class="lead"> Login </p>
            {% include 'accounts/snippets/form.html' with form=login_form next_url=request.build_absolute_uri %}
        </div>
        <div class="col-12 col-md-6">
            <p class="lead"> Continue as Guest </p>
            {% url 'guest_register' as guest_register_url %}
            {% include 'accounts/snippets/form.html' with form=guest_form next_url=request.build_absolute_uri action_url=guest_register_url %}
        </div>
    </div>

    {% else %}

    {% if not object.shipping_address %}

    <div class="row">
        <div class="col-12">
            <p class="lead">Shipping Address</p>
            <hr />
        </div>
        <div class="col-6">
            {% url 'checkout_address_create' as checkout_address_create %}
            {% include 'address/form.html' with form=address_form next_url=request.build_absolute_uri action_url=checkout_address_create address_type='shipping' %}
        </div>

        <div class="col-6">
            {% url 'checkout_address_reuse' as checkout_address_reuse %}
            {% include 'address/prev_address.html' with address_qs=address_qs next_url=request.build_absolute_uri address_type='shipping' action_url=checkout_address_reuse %}
        </div>
    </div>
</div>
</div>

{% elif not object.billing_address %}
<div class="row">
    <div class="col-12">
        <p class="lead">Billing Address</p>
        <hr />
    </div>

    <div class="col-6">
        {% url 'checkout_address_create' as checkout_address_create %}
        {% include 'address/form.html' with form=address_form next_url=request.build_absolute_uri  action_url=checkout_address_create address_type='billing' %}
    </div>
    <div class="col-6">
        {% url 'checkout_address_reuse' as checkout_address_reuse %}
        {% include 'address/prev_address.html' with address_qs=address_qs next_url=request.build_absolute_uri address_type='billing' action_url=checkout_address_reuse  %}
    </div>
</div>


{% else %}
<h1>Finalize Checkout</h1>

<p>Cart total: {{object.cart.total}}</p>
<p>Shipping total: {{object.shipping_total}}</p>
<p>Order total: {{object.total}}</p>
<form class="form" action="" method='POST'>
    {% csrf_token %}

    <button class="btn btn-success" type='submit'>Finish</button>
</form>


{% endif %}
{% endif %}

</div>
{% endblock %}

src/carts/templates/carts/home.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
  <h1>Cart</h1>


  {% if cart.products.exists %}

  <table class="table cart-table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Product name</th>
        <th scope="col">Product price</th>
        <th scope="col">Delete</th>
      </tr>
    </thead>
    <tbody class="cart-body">

      {% for product in cart.products.all %}
      <tr class='cart-product'>
        <th scope="row">{{forloop.counter}}</th>
        <td>
          <a href="{{product.get_absolute_url}}"> {{product.title}}</a>
        </td>
        <td>{{product.price}}</td>
        <td>
          <a href="{{product.get_absolute_url}}"></a>
          {% include 'products/snippets/update-cart.html' with product=product cart=cart in_cart=True %}
        </td>
      </tr>
      {% endfor %}

      <tr>
        <td colspan="3"></td>
        <td><b>Subtotal</b>R$<span class="cart-subtotal">{{cart.subtotal}}</span></td>
      </tr>
      <tr>
        <td colspan="3"></td>
        <td><b>Total</b>R$<span class="cart-total">{{cart.total}}</span></td>
      </tr>
      <tr>
        <td colspan="3"></td>
        <td>
          <a class="btn btn-block btn-success" href="{% url 'cart:checkout' %}">Checkout</a>
        </td>
      </tr>
    </tbody>
  </table>

  {% else %}

  <p class="lead">Cart is empty</p>

  {% endif %}
</div>

{% endblock %}